[package]
name = "cartan"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.0", features = ["image", "canvas"] }
skia-safe = "0.78.0"

tokio = { version = "1.40.0", features = ["full"] }
surf = "2.3.1"
async-std = "1.10"

kuchiki = "0.8"